### PR TITLE
kubeapply improvements

### LINKED ISSUE #77: Parallel kubeapplys are racy
Scenario: There are several parallel processes that each want to idempotently make sure their common dependency is loaded in the cluster, so they each call `kubeapply -f docker-registry.yaml` as part of start up.  If they were run serially, this would work fine; the later invocations of kubeapply would check the cluster, see that it's already applied, and say "no change".  But when they're run in parallel, the check is racy:

   A: check if exists
   B: check if exists
   A: create
   B: create --> Error: already exists

The obvious workaround would be to flock(2) files while they're being processed by `kubectl`.

### PR DESCRIPTION
**Pull request by LukeShu**
CLI-facing changes:
 - Have the timeout be for the whole thing, not per-phase.
 - Fixes #77 

Go-library-facing changes:
 - A lot of stuff moved from `pkg/k8s` to `pkg/kubeapply`.  Nothing that I think was used by anything other than kubeapply, though.
 - Some stuff in `pkg/k8s` that kubeapply uses is now public, because the stuff using it no longer lives in `pkg/k8s`.

Lotsa doc improvements, because `make lint` made me add them with other changes to those files.

### CODE REVIEW

**Comment by LukeShu** [comment]
I've rebased @rhs's commit 0e1476fd764d9b72e40ac64efd8c1cabbd78c000 from #140 on to this, as the `lukeshu/kubapply-improvements-rhs` branch.

**Comment by rhs** [comment]
I like all the cleanup, nice job!

The one question I have is about the timeout change. What's your rationale for making it be total instead of per phase? I would think that would make it difficult to figure out what a good value is since you don't necessarily know how many phases there are and anyone of them could be doing docker pulls and/or waiting for servers to spin up. In theory if it's a per-phase timeout you are just supplying how long you are willing to wait for a deployment to spin up.

**Comment by LukeShu** [comment]
My rationale for the global instead of per-phase timeout:
 - I was 100% surprised when reading the code to discover that it was per-phase.  To the degree that my initial reaction is "this must be a bug".
 - Something I'd like to implement, but haven't gotten around to yet, is having multiple streams of phases.  If I run `kubeapply -f dirA -f dirB`, then `dirB/02-*` should block on `dirB/01-*`, but not `dirA/01-*`.  With a per-phase timeout, reasoning about the timeouts there gets trickier.

With in-total or per-phase timeout, either way, it's the case that anything could include a Docker pull.  Maybe thinking "how long do I expect the slowest phase to take" is maybe easier than thinking "how long do I expect the entire thing to take".  Maybe, IDK.

Reflecting on it now, going the other way and being more granular might make a lot of sense; having it be a per-resource timeout.

**Comment by LukeShu** [comment]
Reflecting on that more, total might make more sense for an end-user, but for determining the default value, per-phase definitely is the saner choice.  I'll revert that bit tomorrow.

**Comment by LukeShu** [comment]
@rhs I just pushed another commit rolling back to having timeouts be per-phase.

**Pull request merged**
