### PR TITLE
edgectl: Add a smoke test for outbound

### PR DESCRIPTION
**Pull request by ark3**

### CODE REVIEW

**Comment by LukeShu** [comment]
I feel like this should be using `dtest.WithNamedMachineLock`?

I have no insight as to what's going on with the macos build.

**Comment by ark3** [comment]
Ha! You are correct. As with the Teleproxy tests, this will need to run with the default machine lock, since Edge Control Daemon and Teleproxy are mutually incompatible (by virtue of being the same).

**Comment by LukeShu** [comment]
Yeah, I needed to read it closer.

Maybe the issue is that `testprocess.Dispatch()` is outside of the `dtest.WithMachineLock`?

**Comment by ark3** [comment]
Nah, dispatch wants to be outside, as it is for Teleproxy tests. The issue (on MacOS) seems to be that _something_ is taking a long time, edgectl tests wait around for that time to get the lock, and then they themselves take long enough that either Go Test or Circle kill things.

**Pull request closed without merging**
